apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: ${EXTERNAL_DNS_ROLE_ARN}
automountServiceAccountToken: true